from asyncore import poll
from lib2to3.pgen2.token import SLASHEQUAL
import re
from Carnes import Carnes
from Comida import *
from Dulces import Dulces
from Harinas import Harinas
from Lacteos import *
from VerdurasYFtutas import *
from receta import *
from funcionesN import *

tomate=VerdurasYFtutas(1,"tomate","3-8 dias conservandose al aire libre",4,"es una verdura que normalmente se usa para hacer guizo o para hacer ensalada","Cuando el vegetal esta maduro , tiene un color rojizo con una forma redonda y un centro aguado","contiene bastantes atioxidantes")
cebollaC=VerdurasYFtutas(2,"cebolla cabezona","7-15 dias conservandose al aire libre",4,"es una verdura que se usa para hacer guizo o para sofreir","tiende a tener un largo de 25-30 centrimetros con una cabeza verde y un cuerpo blanco , la cabez no se usa al momento de cocinar","tiene componentes que ayudan al sistema nervioso")
cebollaL=VerdurasYFtutas(3,"cebolla larga","7-15 dias conservandose al aire libre",4,"es una verdura blanca que se usa para hacer guizo, ensaladas o para madurar carnes ","tiene un cuerpo redondo el cual suele tener un diametro entre 5-15 cm","es buena para le sistema nervioso")
papaP=VerdurasYFtutas(4,"papa pastusa","10-20 dias conservandose al aire libre",4,"es un tuberculo que se suele cocinar para servirse salado o con cascara o se puede hacer pure ","tiene un cuerpo redondo el cual con una cascara entre negra y parda , por su interior es blanca suele tener un diametro entre 5-15cm","contiene bastante potasio")
papaC=VerdurasYFtutas(5,"papa criolla","10-20 dias conservandose al aire libre",4,"es un tuberculo que se suele cocinar o fritar entera o tajada para luego salarse ","es un tuberculo que con una cascara amarilla por dentro tiene un mismo color ,  suele tener un diematro entre unso 2-5 cm ","contiene potasio ")
pepinoE=VerdurasYFtutas(6,"pepino de ensalada","7-15 dias conservandose al aire libre",4,"es un vegetal que se suele picar para hacer ensaladas ","Tiene un cuerpo largo entre 15-30 centiretros con un cuerpo y cascara de color verdoso,suele tener un diematro entre unso 2-5 cm ","")
pepinoG=VerdurasYFtutas(7,"pepino de guiso","7-15 dias conservandose al aire libre",4,"es un vegetal que se suele cocinar para hacer guiso ","Tiene un cuerpo ovalado con un largo entre 10-20 centiretros con un cuerpo y cascara de color verdoso , suele tener un diematro entre unso 2-5 cm ","")
calabaza=VerdurasYFtutas(8,"calabaza","10-20 dias conservandose al aire libre",4,"es un vegetal que se suele cocinar con o sin cascara para luego hacerla pure o servirla cortada","Tiene un cuerpo ovalado el cual nolmamente tiene una forma de bolo con un largo entre 15-25 centiretros con una cascara de color verdoso y un ineterior de color naranja amarilloso","")
manzana=VerdurasYFtutas(9,"manzana","3-7 dias conservandose al aire libre",4,"Es una fruta la cual se come directamente , se recomienda cortar o lavar la cascara ","tiene un cuerpo redondo con un diametro entre 5-10cm , una cascara roja y un interior blanco","")
zanahoria=VerdurasYFtutas(10,"zanahiria","7-15 dias conservandose al aire libre",4,"Es un vegetal el cual se suele picar o rayar para acompañar varias preparaciones","tiene un cuerpo en forma de cono con una longitud entre 8-15cm con una cascara y un interior de color naranja ","")
mandarina=VerdurasYFtutas(11,"mandarina", "10-20 días en conservación al aire libre",4,"Es una fruta que comunmente se come fresta o en su defecto al ser un citrico, en jugos naturales junto a otras frutas del mismo tipo","tiene forma redonda y su longitud es de aproximadamente es de 5-8 cm de diametro.","Está repleta de vitamina C")
aji=VerdurasYFtutas(12,"ají","10 días de conservación, refrigerados frescos",4,"Se usa principalmente como especia, ya sea en polvo  o picado, tiene la propiedad de aportar mucho sabor y picor a las comidas","mide 4,27 mm de largo y 1,40 mm de ancho. La mayoría de las especies.","Sus propiedades medicinales abarcan desde la estimulación del apetito hasta la cura de la depresión")
apio=VerdurasYFtutas(13,"apio","3-4 semanas refrigerado ",4,"Se usa principalmente en caldos, arroces, sopas para portar sabor, además de que en muchas ocasiones se come crudo debido a sus propiedades","el apio debe ser de 15 cm de diámetro, con un largo aproximado de 50 cm y un peso superior a 1 kg","Tiene vitaminas B y K, así como ácido fólico y minerales como el potasio, magnesio, calcio, sodio y hierro.")
cilantro=VerdurasYFtutas(14,"cilantro","Se conserva hasta 2 semanas refrigerado",4,"Se usa principalmente en la prepareción de  caldos, lentejas, frijoles, sopas, arroces, etc","Es de hábito anual y bajo condiciones normales, el cilantro alcanza de 40 a 60 cm de altura.","Tiene propiedades antibacterianas y evita la proliferación del virus de la Salmonella en los alimentos.")
Maiz=VerdurasYFtutas(15,"maíz","Se puede conservar hasta por 3 días",4,"Su uso se da principalmente en harinas, feculas, palomitas, sopas y elotes","Su tamaño no supera el centimetro de diametro. Es de tamaño ovalado y crece en forma conica, conocido comunmente como Mazorca","Tiene antioxidantes")
ajo=VerdurasYFtutas(16,"ajo","Los ajos pueden conservarse a temperatura ambiente hasta 3 meses.",4,"El ajo puede consumirse crudo o cocido, por lo que tiene varios usos: los dientes crudos, enteros y pelados se frotan directamente sobre pan para aromatizarlo y se licuan en salsas, moles y pipianes; picados se utilizan para sazonar verduras crudas o para dar sabor a mantequillas","es chato en la base, con un diámetro ecuatorial entre 3 y 8 cm"," una fuente rica en magnesio, selenio y vitamina C")
chili=VerdurasYFtutas(17,"chili","Pueden conservarse hasta 3 meses sellado.",4,"El chili es una especie comunmente utilizada para aportar sabor, picor y amplicamente aplicado en la cocina mexiana","Es una alimento granulado","Actúa como analgésico, es una buena fuente de vitamina A y mejora la circulación.")
comino=VerdurasYFtutas(18,"comino","Pueden conservarse hasta 3 meses sellado.",4,"Las semillas de comino añaden un sabor algo picante y un fuerte aroma a los platos. ","Es una especie que puede presentarse de forma granulada o en pequeñas piezas","Es una fuente rica de hierro y fortalece el sistema inmunológico.")
mostaza=VerdurasYFtutas(19,"mostaza","Puede conservarse hasta 3 semanas a termperatura ambiente ",4," La mostaza en semillas sirve para condimentar marinadas y elaborar carnes en salsa, mientras que los preparados se usan más como condimento o como base de otras salsas.","Se puede presentar como salsa, grano o incluso aceite"," Ayuda a bajar de peso y mantener bajo control los síntomas del asma.")
pimienta=VerdurasYFtutas(20,"pimienta Negra","Puede conservarse a temperatura ambiente por varios meses",4,"La pimienta es un alimento fundamental en toda cocina, puesto que esta realza todos los sabores de los platillos","Es un grano grande, que comunmente se muele para aprovechar su sabor","También ayuda a reducir los problemas respiratorios, tos y resfrío.")
huevo=Lacteos(21,"huevo","Puede conservarse a temperatura ambiente por varias semanas",3,"Uno de los ingredientes más versátiles de la cocina, fritos, revueltos, en masas, hervidos, etc.","Es ovalado, con un contenido liquido, con cascara","Es una gran fuente de proteina")
miel=Dulces(22,"miel","Puede conservarse por demasiado tiempo, en las condiciones adecuadas",1,"Uno de los ingredientes fundamentales para dar dulzor a los alimentos","Es un liquido viscoso y dorado, producido por abejas","Una rica fuente de vitamina C, calcio y hierro.")
aceitunas=VerdurasYFtutas(23,"Aceitunas","Dentro de las condicionesa adecuadas, pueden durar hasta 3 semanas en salmuera",4,"Su uso es mayormente en conserva, completas en salmuera a manera de snack.","Son verdes, de forma ovalada y a veces con centro rojo, su sabor es fuerte,","Mejora la circulación sanguinea y estabiliza la presión")
queso=Lacteos(24,"queso","El queso es  un alimento que puede durar de 15-20 días",3,"El queso es un alimento versatil que se puede utilizar para ensaldas, gratinar, salsas, postres, etc","Su forma depende del molde, pero casi siempre es de un color blanquecino","contiene calcio, proteínas y vitaminas.")
arroz=Harinas(25,"arroz","El arroz es un alimento que puede dura de 4-5 días preparado",5,"Es un alimento fundamental, utilizado en casi todo tipo de plato como acompañante por sí solo.","Su forma es granulada, con forma ovalada","Rico en proteínas, calcio, magnesio, fibra y potasio.")
azucar=Dulces(26,"azucar","La azucar puede durar un periodo de hasta 2 años en buenas condiciones",4,"Es un alimento primordial para cualquier postre, al proporcionar dulzor","Su forma es granulada en cristales muy pequeños","El azucar es importante para controlar la insulina en el organismo.")
jengibre=VerdurasYFtutas(27,"jengibre","El jengibre es una raiz que puede durar varias semanas en buenas condiciones",4,"Se ha utilizado para ayudar a la digestión, reducir la náusea y ayudar a combatir la gripe y el resfriado común","Al ser una raiz, su forma varía mucho, en cada pieza","mejora los problemas gastrointestinales, reduce mareos, vómitos y dolor de cabeza.")
limon=VerdurasYFtutas(28,"limon ","El limón puede durar hasta 5 semanas en buen estado.",4,"Es perfecto para hacer jugos naturales. aportar toques de acidez y limpiar algunos alimentos","Tiene una forma ovalada, o esferica dependiendo del tipo ","Tiene una gran cantidad de vitamina C y propiedades de conservación.")
manzana=VerdurasYFtutas(29,"manzana","Una manzana puede estar fresca hasta un mes en buenas condiciones",4,"Las manzanas son ampliamente usadas en postres, jugos y nectar.","Su forma es ovalada y dependiendo de la especie puede ser gran o pequeño tamaño","tiene una gran concentración de nutrientes, antioxidantes y ayuda a librarte de carcinógenos.")
hongos=VerdurasYFtutas(30,"hongos","Pueden sobrevivir 4 días a temperatura ambiente ",4,"Son ampliamente usados en pizzas, ensaladas y cremas "," Tienen forma de cupcake y su tamaño depende del tipo y especie","Tienen antioxidantes  y vitaminas naturales")
vinagre=Dulces(31,"vinagre","El vinagre puede persistir hasta 4 semanas en buenas",1,"Este ingrediente es ampliamente usado en ensaldas de todo tipo","Es liquido y transparente","Ayuda mucho al correcto funcionamiento del sistema nervioso")
avena=Lacteos(32,"avena","Este alimento puede tardar de 2-3 meses en buen estado",3,"Este ingrediente versatil es ampliamente usado para postres, galletas, etc","Es granulado y blanquecino.","Es perfecto para mejorar la digestión y aumentar la fibra")
pan=Harinas(33,"pan","Puede durar en buen estado hasta 2 meses",5,"Este ingrediente, es ampliamente usado en prepareciones sencillas como sanduches, hamburguesas, etc","esferico, dorado y esponjoso.","Es una fuente muy buena de carbohidratos")
frijoles=Harinas(34,"frijoles","Tiene una vida util de hasta 3 meses",5,"Este ingrediente es ampliamente usado en la elaboración de casuelas, bandejas y comidas mexicanas","Su forma es esferica y pequeña, al ser un grano ","Es una muy buena fuente de fibra")
lechuga=VerdurasYFtutas(35,"lechuga","Tiene una vida util de 3 días",4,"Este alimento es fundamental en la elaboración de ensaladas y platillos vegetarianos","Es una hoja, por tal razón es alargada","Es muy nutritiva, al estar llena de antioxidantes")
perejil=VerdurasYFtutas(36,"perejil","Se conserva hasta 2 semanas refrigerado",4,"Se usa principalmente en la prepareción de  caldos, lentejas, frijoles, sopas, arroces, etc","Es de hábito anual y bajo condiciones normales, el cilantro alcanza de 40 a 60 cm de altura.","Tiene propiedades antibacterianas y evita la proliferación del virus de la Salmonella en los alimentos.")
pollo=Carnes(37,"pollo","Tiene un periodo de consevación de 2-3 días ",2,"Es una proteina versatil que se usa como plato principal, ya se asado, frito, hervido, etc","Es una ave de corral","Es una increible fuente de proteina")
res=Carnes(38,"carne de Res","Tiene un periodo de consevación de 2-3 días ",2,"Es una proteina versatil que se usa como plato principal, ya se asada, frita, hervida, etc","Puede ser cualquier forma debido al corte","Es una increible fuente de proteina")
cerdo=Carnes(39,"carne de Cerdo","Tiene un periodo de consevación de 2-3 días ",2,"Es una proteina versatil que se usa como plato principal, ya se asada, frita, hervida, etc","Puede ser cualquier forma debido al corte","Es una fuente de proteina")
mariscos=Carnes(40,"mariscos","Tiene un periodo de consevación de 2-3 días ",2,"Es una proteina versatil que se usa como plato principal, ya se asado, frito, hervido, etc","Puede ser cualquier forma debido al corte","Es una increible fuente de proteina")
pato=Carnes(41,"pato","Tiene un periodo de consevación de 2-3 días ",2,"Es una proteina versatil que se usa como plato principal, ya se asado, frito, hervido, etc","Es una ave de corral","Es una increible fuente de proteina")
salsatomate=VerdurasYFtutas(42,"salsa de Tomate","Tiene un periodo de conservación de 4 semanas",4,"Es un increible adobo para carbohidratos, arroces, etc.","Tiene una forma liquida y color rojizo","Tiene antioxidantes")
mayonesa=Lacteos(43,"mayonesa","Tiene un periodo de conservación de 4 semanas",3,"Es un increible adobo para carbohidratos, arroces, etc.","Tiene una forma liquida y color blanquezino","Tiene antioxidantes")
sal=VerdurasYFtutas(44,"sal","Tiene un periodo indefinido de conservación",4,"Es el sasonador por excelencia para realzar los sabores","Tiene una forma granulada al ser cristalina y blanquecina","Ayuda a no retener tantos liquidos" )



def todosLosIngredientes():
    listatotalI=[tomate,cebollaC,cebollaL,papaP,papaC,pepinoE,pepinoG,calabaza,manzana,zanahoria,mandarina,aji,apio,cilantro,Maiz,ajo,chili,comino,mostaza,pimienta,huevo,miel,aceitunas,queso,arroz,azucar,jengibre,limon,manzana,hongos,vinagre,avena,pan,frijoles,lechuga,perejil,pollo,res,cerdo,mariscos,pato,salsatomate,mayonesa,sal]
    return listatotalI

receta1=receta(100,"Pasta con pollo","Pondremos a calentar la pasta durante 20 min , cosinameros y luego desmechamos el pollo , para luego guisar y finalmente unir con la pasta",[tomate,cebollaL],"Sal , color , oregano y salsa de champiñones")
receta2=receta(101,"Arroz con papa","Pondremos a cocinar el arroz con cebolla cabezona , y fritaremos las papas. Luego servimos",[papaP,cebollaC,arroz,sal],"Sal")
receta3=receta(102,"Spaguettis con Pechuga","PASO 1 Cocina la pasta, En una olla de fondo alto agrega 8 tazas de agua, lleva a fuego alto hasta que el agua hierva, agrega la pasta y deja cocinar por 9 minutos, pasado el tiempo de cocción retira del fuego, escurre el agua en un colador y reserva.PASO 2 Cocina la pechuga. Saca las 4 láminas que vienen dentro del sobre de JUGOSO AL SARTÉN MAGGI® PIMENTÓN, pon en cada lámina una porción de pechuga y lleva a fuego medio en una sartén de teflón 8 minutos por cada lado. Pasado el tiempo retira las láminas con las pechugas dentro, pasa a una tabla, corta cada pechuga en trozos pequeños y reserva. PASO 3 Prepara la salsa. Pon una olla de fondo alto a fuego medio y derrite la mantequilla, agrega la cebolla, el tomate, la sal, pimienta®, sofríe por 2 minutos, agrega la leche y deja por 3 minutos más, integra la pasta y deja cocinar por 1 minuto más.PASO 4 Sirve. Sirve cada porción de pasta y pon encima una porción de trozos de pechuga.",[sal,salsatomate,pollo,pimienta,tomate,cebollaC],"Spaguetti")
receta4=receta(103,"Revoltillo con huevo.","Usa 2 huevos por persona, revuelvelos suavemente mientras los fritas, en movimientos circulares,agregea sal. Puedes hacer estre proceso con mantequilla o aceite. Después unta un poco de mantequilla a los panes y sirve a tu gusto.",[pan,huevo,sal],"Mantequilla")
receta5=receta(104,"Sopa de pollo","Hierve una pieza de pollo de tu preferencia a esto agregale los vegetales sugeridos en la receta, un poco de sal, pimienta. Todo esto por un periodo de tiempo de 1 hora si es para más de 4 personas.  Esto lo puedes acompañar con arroz.",[sal, pimienta, pollo, papaC,cilantro,apio,aji,ajo,zanahoria,Maiz,arroz],"")
receta6=receta(105,"Sopa de carne","Hierve una pieza de carne (preferiblemente carne) a esto agregale los vegetales pelados y picados finamente sugeridos en la receta, un poco de sal, pimienta. Todo esto por un periodo de tiempo de 1 hora si es para más de 4 personas.  Esto lo puedes acompañar con arroz.",[sal, pimienta, res, papaC,cilantro,apio,aji,ajo,zanahoria,Maiz,arroz],"")
receta7=receta(106,"Coctel de Camarón","Hierve camarón hasta que cambien de color, a esto agregale los vegetales pelados y picados finamente sugeridos en la receta, un poco de sal, pimienta, salsa de tomate y mayonesa, además de limón.",[sal, pimienta, salsatomate, mayonesa,cilantro],"camarón")
receta8=receta(107,"Pollo guisado y arroz","Hierve el pollo junto a los vegetales sugeridos en la receta, agrega sal, pimienta, papas picadas en cuadros y espera a que todo quede en su termino. Lava el pollo anteriormente con limón y lo acompañas con arroz al gusto.",[sal, limon, pollo, papaP, cebollaC, tomate, pimienta,aji,ajo,mostaza],"")
receta9=receta(108,"Carne guisada y arroz","Hierve la carne junto a los vegetales sugeridos en la receta, agrega sal, pimienta, papas picadas en cuadros y espera a que todo quede en su termino. Agrega el limón en la prepareción, al sellar la carne. Y lo acompañas con arroz al gusto",[sal, limon, res, papaP, cebollaC, tomate, pimienta,aji,ajo,mostaza],"")
receta10=receta(109,"Cerdo guisado y arroz","Hierve la carne de cerdo junto a los vegetales sugeridos en la receta, agrega sal, pimienta, papas picadas en cuadros y espera a que todo quede en su termino. Agrega el limón en la prepareción, al sellar la carne. Y lo acompañas con arroz al gusto",[sal, limon, res, papaP, cebollaC, tomate, pimienta,aji,ajo,mostaza],"")
receta11=receta(110,"Papas con huevos rotos","Precalentar el horno a 180° C. (temperatura alta) Pelar las papas y cortarlas en cubos de 2 x 2 cm, pre cocerlas en agua hirviendo por 10 minutos aproximadamente, reservar. En una bandeja de horno acomodar las papas y rociarlas con la grasa, hornear hasta que estén doradas y crocantes , aproximadamente 25 minutos. En una licuadora poner la pasta de ajo, el zumo de limón y la mayonesa, licuar a velocidad media, incorporar en forma de hilo la leche, procesar hasta obtener una salsa untuosa. Servir una cama de papas, los huevos tibios partidos por la mitad y bañar con el alioli, decorar con perejil picado.",[papaC,huevo,sal,pimienta],"")
receta12=receta(111,"Papas chorreadas con pollo","Calentar papas hasta obtener que queden semiblandas, echar pasta de tomate, salsa de tomate y mucho queso a la preparación, degustar con sal y pimienta",[sal, pimienta, papaP, queso, salsatomate],"")
receta13=receta(112,"Ensalada de papa","Hervir papa, echarle mayonesa, huevo hervido, cilantro, sal, pimienta y limón",[papaC, mayonesa,huevo,cilantro,sal,pimienta,limon],"")
receta14=receta(113,"Arroz de pollo","Cortar pollo finamente, y echarlo en el agua del arroz para que adquiera sabor, adobar con sal, cilantro, perejil, ají, ajo y por ultimo servir con salsa de tomate",[sal,pollo,aji,ajo,perejil, cilantro],"")
receta15=receta(114,"Arroz de cerdo","Cortar pollo finamente, y echarlo en el agua del arroz para que adquiera sabor, adobar con sal, cilantro, perejil, ají, ajo y por ultimo servir con salsa de tomate",[sal,cerdo,aji,ajo,perejil, cilantro],"")
receta16=receta(115,"Pechuga a la mostaza y limón","Cortar la pechuga en tiras largas, limpiarlas con limón, adobarlas con mostaza,ajo, sal y pimienta, sofreirlas hasta dorarlas y degustar",[ajo, sal, pimienta, pollo, mostaza,limon],"")
receta17=receta(116,"Tortilla de huevo","Utilizar tres cucharadas de arroz frío, mezclarlo en un huevo batido. Hasta homogenizar, despues de esto, con aceite o mantequilla, se fríe la tortilla hasta que se pueda voltear, adobar la mezcla con sal y pimienta.",[sal, pimienta,huevo, arroz],"Mantequilla")
receta18=receta(117,"Tortilla española","Freir papas en cubos, hasta que ablande, echar un total de 2 huevos, batidos al sartén. Sazonar con sal, pimienta y ajo granulado.",[ajo,sal,pimienta,huevo,papaC],"")
receta19=receta(118,"Te de jengibre con limon","Hierve agua con jengibre picado, hasta hervir, para servir, adiciona limon y miel",[miel, limon, jengibre,miel],"")
receta20=receta(119,"Te de limón y miel","Coloca agua al fuego hasta que hierva, sirve adicionando limón y miel,",[limon, miel],"")
receta21=receta(120,"Arroz con frijol","Haz un sofrito con cebolla, tomate, sal, aji y pimienta. Con frijoles que hayas puesto en agua el día anterior, ponlo en una olla a presión por 20 minutos, después de este tiempo, adiciona el sofrito, espera 15 minutos más y sirve con arroz.",[frijoles,tomate,cebollaC,sal,pimienta,arroz],"")
receta22=receta(121,"Batido de Avena","Licua avena, con leche, azucar, una cucharada de miel y sirve al gusto.",[miel,azucar,avena],"")
receta23=receta(122,"Hotcakes saludables","Después de moler la avena, agregas un huevo a la mezcla, con un chorro de vainilla y se debe licuar. Se sirve con rodajas de manzana encima",[manzana,avena,huevo],"Vainilla")
receta24=receta(123,"Ensalada basica","Pica tomate, cebolla, lechuga, junta todo esto al gusto, con sal, pimienta y limón",[sal, pimienta, limon,cebollaC,tomate,lechuga],"")
receta25=receta(124,"Crema de Champiñon","Licuas los hongos con caldo de pollo, sal, pimienta. Al servir adicionar, cilantro, perejil y a degustar",[sal, pimienta,hongos,perejil,cilantro],"")
receta26=receta(125,"Ensalada de manzana","Pica manzanas en cubos, junto a papa hervida, mayonesa y maiz. Adiciona sal y pimienta al gusto. Todo esto se sirve frío después de unos 15 minutos de refrigeración",[sal,pimienta,manzana,papaP,mayonesa, Maiz],"")
receta27=receta(126,"Carne molida","Prepara un sofrito de tomate, cebolla, ají, ajo, sal y pimienta. Adiciona la carne molida cucando este sofrito esté completamente liquido y sigue preparando hasta secar. Puedes acompañarlo con arroz-",[res,tomate, cebollaL, sal,pimienta,aji,ajo],"")

def todasLasRecetas():
    listatotalR=[receta1,receta2,receta3,receta4,receta5,receta6,receta7,receta8,receta9,receta10,receta11,receta12,receta13,receta14,receta15,receta16,receta17,receta18,receta19,receta20,receta21,receta22,receta23,receta24,receta25,receta26,receta27]
    return listatotalR
